config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks", :passwords => "users/passwords" }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get "register" => "devise/registrations#new"
    get 'verification' => 'devise/registrations#verification'
    post 'verify_user' => 'users/registrations#verify_user'
    post 'verify_otp' => 'users/registrations#verify_otp'
  end

  root 'home#index'
  resources :orders do
    collection do
      post 'quick_order'
      post 'track_order'
    end
  end
  get 'pricing' => 'home#pricing'
  get 'faqs' => 'home#faqs'
  get 'contact_us' => 'home#contact_us'
  resources :coupons do
    collection do
      post 'apply_coupon'
    end
  end
  
  #Api definition
  namespace :api, defaults: { format: :json } do

    scope module: :v1 do
      #List our resources here
      resources :users, :only => [:index, :show, :create, :update, :destroy]
      resources :orders, :only => [:index, :show, :create]
      resources :sessions, :only => [:create, :destroy]
    end

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunGallery</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="alert_html">
  <% if notice %>
    <div class="alert alert-info alert_top_spacing">
        <button class="close" data-dismiss="alert" type="button">
            &times;
        </button>
        <%= notice %>
    </div>
  <%end %>
  <% if alert %>
    <div class="alert alert-info alert_top_spacing">
        <a class="close" data-dismiss="alert" href='#'>&times;</a>
        <%= simple_format(alert) %>
    </div>
  <%end %>
  <% if flash[:error] %>
    <div class="alert alert-info alert_top_spacing">
      <a class="discard_contacts close" data-dismiss="alert" href='#'>&times;</a>
      <%= simple_format(flash[:error]) %>
    </div>
  <%end %>
</div>
<!-- Body Wrapper -->
<div class="wrapper white">

	<!-- Header Start -->
	<div class="header">
		<!-- Header Information -->
		<div class="header-info">
			<div class="container">
				<div class="row">
					<div class="col-md-2 col-sm-2">
						<!-- Social Media -->
						<div class="social">
							<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
							<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
							<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
						</div>
					</div>
					<%= form_tag track_order_orders_path do |f| %>
						<div class="col-md-3 col-sm-3">
							<div class="form-group">
								<div class="col-sm-12">
									<div id="imaginary_container"> 
						                <div class="input-group stylish-input-group">
						                    <%= text_field_tag :tracker, nil, class: "form-control", placeholder: "Track order, Enter Order No"%>
						                    <span class="input-group-addon">
						                        <button type="submit">
						                            <span class="fa fa-search"></span>
						                        </button>  
						                    </span>
						                </div>
						            </div>
								</div>
							</div>
						</div>
					<%end%>
					<div class="col-md-3 col-sm-3">
							<!-- Contact Info -->
						<div class="contact-info">
							<span><i class="fa fa-phone br-lblue"></i> <strong>+91 94630-83099</strong></span>
						</div>
					</div>
					<% if user_signed_in?%>
						<div class="col-md-4 col-sm-4">
							<!-- Contact Info -->
							<div class="contact-info">
									<span><strong>Hi, <%= current_user.email%></strong></span>
							</div>
						</div>
					<%else%>
						<div class="col-md-4 col-sm-4">
							<!-- Contact Info -->
							<div class="contact-info">
									<span><strong>Hi, Guest</strong></span>
							</div>
						</div>
					<%end%>
				</div>
			</div>
		</div>
		<!-- Header Navigation -->
		<div class="header-navigation">
			<div class="container">
				<div class="row">
					<div class="col-md-5">
						<!-- Logo -->
						<div class="">
							<!-- Heading -->
							<a href="/"><img src="/img/ml_logo.png" class="img-responsive" alt="" height="107px" /></a>
						</div>
					</div>
					<div class="col-md-7">
						<!-- Bootstrap Navbar -->
						<nav class="navbar navbar-default" role="navigation">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header">
								<button type="button" class="navbar-toggle br-orange" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
							</div>
							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
								<ul class="nav navbar-nav navbar-right">
									<li>
										<a href=<%= root_url%> class="br-orange">
											<!-- Link Icon -->
											<i class="fa fa-home link-icon"></i>
											<!-- Link Title -->
											<span class="link-title">Home</span>
										</a>
									</li>
									<li>
										<a href="/pricing" class="br-red">
											<!-- Link Icon -->
											<i class="fa fa-money link-icon"></i>
											<!-- Link Title -->
											<span class="link-title">Pricing</span>
										</a>
									</li>
									<% if controller_name == "home" and action_name == "index"%>
										<li>
											<a href="/faqs" class="br-purple">
												<!-- Link Icon -->
												<i class="fa fa-book link-icon"></i>
												<!-- Link Title -->
												<span class="link-title">Faqs</span>
											</a>
										</li>
										<li>
											<a href="/contact_us" class="br-green">
												<!-- Link Icon -->
												<i class="fa fa-comment link-icon"></i>
												<!-- Link Title -->
												<span class="link-title">Contact</span>
											</a>
										</li>
										<!--<li>
											<a href="index.html" class="br-pink">
												<i class="fa fa-user link-icon"></i>
												<span class="link-title">About Us</span>
											</a>
										</li>-->
									<%end%>
									<li>
										<a href=<%= new_order_path%> class="br-blue">
											<!-- Link Icon -->
											<i class="fa fa-plane link-icon"></i>
											<!-- Link Title -->
											<span class="link-title">Order Now</span>
										</a>
									</li>
									<li>
										<% if user_signed_in?%>
											<%= link_to logout_path, :method => :delete, class: "br-lblue" do%>
												<!-- Link Icon -->
												<i class="fa fa-sign-out link-icon"></i>
												<span class="link-title">Sign Out</span>
												<!-- Link Title -->
											<%end%>
										<%else%>
											<a href=<%= login_path %> class="br-lblue">
												<!-- Link Icon -->
												<i class="fa fa-sign-in link-icon"></i>
												<!-- Link Title -->
												<span class="link-title">Sign In</span>
											</a>
										<%end%>
									</li>
								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Header End -->
	<%= yield %>
	<!-- Footer Start -->

	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<!-- Footer Widget -->
					<div class="footer-widget">
						<!-- Logo Icon -->
						<!-- Heading -->
						<a href="/"><img src="/img/ml_logo.png" class="img-responsive" alt="" height="107px" /></a>
						<!-- Paragraph -->
						<p>Welcome to Mother's Laundry.</p>
						<!-- Social Media -->
						<div class="social">
							<a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
							<a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
							<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
						</div>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<!-- Footer Widget -->
					<div class="footer-widget">
						<!-- Heading -->
						<h5><i class="fa fa-plus br-red"></i> Navigation Menu</h5>
						<div class="row">
							<div class="col-md-6 col-sm-6 col-xs-6">
								<!-- Menu Icons link -->
								<ul class="list-unstyled">
									<li><a href="/"><i class="fa fa-home br-red"></i> Home</a></li>
									<li><a href="/contact_us"><i class="fa fa-phone br-green"></i> Contact Us</a></li>
								</ul>
							</div>
							<div class="col-md-6 col-sm-6 col-xs-6">
								<!-- Menu Icons link -->
								<ul class="list-unstyled">
									<li><a href="#services"><i class="fa fa-gear br-lblue"></i> Service</a></li>
									<li><a href="#testimonial"><i class="fa fa-comment br-purple"></i> Testimonial</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix visible-sm"></div>
				<div class="col-md-3 col-sm-6">
					<!-- Footer Widget -->
					<div class="footer-widget">
						<!-- Heading -->
						<h5><i class="fa fa-map-marker br-yellow"></i> Contact Us</h5>
						<address>
							<i class="fa fa-home br-green"></i> #9 Street 1 <br />
							&nbsp; &nbsp; &nbsp; &nbsp; Ramlal Nagar, Malwal Road  <br />
							&nbsp; &nbsp; &nbsp; &nbsp; Ferozepur City 152002 <br />
							<span><i class="fa fa-phone br-orange"></i> +91 94630 83099</span>
							<span><i class="fa fa-envelope-o br-blue"></i> <a href="#">abc@example.com</a></span>
						</address>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<!-- Footer Widget -->
					<div class="footer-widget">
						<!-- Heading -->
						<h5><i class="fa fa-location-arrow br-lblue"></i> Location</h5>
						<!-- Google Map -->
						<div class="map">
							<!-- Image -->
							<img src="/img/map.png" class="img-responsive" alt="" />
							<!-- Map Marker -->
							<i class="fa fa-map-marker marker india lblue"></i>
						</div>
						<span class="location-name">
							<i class="fa fa-map-marker br-lblue"></i> India &nbsp;&nbsp;
						</span>
					</div>
				</div>
			</div>
			<!-- Footer Copyright -->
			<div class="footer-copyright">
				<p>&copy; Copyright 2017 <a href="#">Mother's Laundary</a></p>
			</div>
		</div>
	</div>
</div>
		<script type="text/javascript" >
		
		// Type your codde here
		</script>
</body>
</html>